In [1]:
import numpy as np

#10

In [13]:
#10
arr = np.zeros((5,5), int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
np.fill_diagonal(arr, 1)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#4

In [29]:
#4
bar = np.array([[[5, -15, 15, 20],
                 [25, -30, 35, 40],
                 [45,  50, -7, -60]]])
bar

array([[[  5, -15,  15,  20],
        [ 25, -30,  35,  40],
        [ 45,  50,  -7, -60]]])

In [30]:
bar[bar < 0] = 0
bar

array([[[ 5,  0, 15, 20],
        [25,  0, 35, 40],
        [45, 50,  0,  0]]])

#5

In [47]:
arr2 = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr3 = np.array([[0, 53, 10],
       [2, 9, -3],
       [1, 15, 24]])

In [49]:
arr2.put([1, 3, 5], arr3)

In [50]:
arr2

array([[ 1,  0,  3],
       [53,  5, 10],
       [ 7,  8,  9]])

#6

In [54]:
arr4 = np.array([[1, 2, 0],
                 [0, 5, 6],
                 [7, 0, 9]])

In [59]:
index = np.argwhere(arr4 == 0)

In [61]:
index #індекси нульових елементів

array([[0, 2],
       [1, 0],
       [2, 1]])

#7

In [62]:
arr5 = np.array([[ 1,  0,  3],
                 [53,  5, 10],
                 [ 7,  8,  9]])

In [65]:
rows = arr5[[1]]

In [67]:
rows #Другий рядок(перший за порядком)

array([[53,  5, 10]])

#9

In [71]:
arr6 = np.array([[ 1,  0,  3],
                 [53,  5, 10],
                 [ 7,  8,  9]])

In [75]:
rownumb  = np.where(np.any(arr6 > 7, axis = 1)) #Візьмемо число 7 за x

In [77]:
rownumb #номери рядків які містять числа > x(7)

(array([1, 2]),)